<?php

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use App\Entity\Stage;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;



class NewStageType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $stage = new Stage();

        $builder

            ->add('stage_no', TextType::class, array(
                'attr' => array('class' => 'form-control')
            ))



            ->add('date_due', DateType::class, array(
                'widget' => 'single_text',
                'attr' => array('class' => 'form-control'),
                'required' => false))

            ->add('notes', TextareaType::class, array('attr' => array('class' => 'form-control'), 'required' => false))
            ->add('budget_hours', TextType::class, array('attr' => array('class' => 'form-control'), 'required' => false))
            ->add('budget_setrate', TextType::class, array('attr' => array('class' => 'form-control'), 'required' => false))
            ->add('completed_hours', TextType::class, array('attr' => array('class' => 'form-control'), 'required' => false))

            ->add('save', SubmitType::class, array(
                'label' => 'Create',
                'attr' => array('class' => 'btn btn-primary mt-3')
            ))
            ->getForm();

    }

}